---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fb-app
  namespace: stage
  labels:
    app: fb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fb-app
  template:
    metadata:
      labels:
        app: fb-app
    spec:
      containers:
      - name: frontend
        image: chuckberry321/13-kubernetes-config_frontend
        ports:
        - containerPort: 80
      - name: backend
        image: chuckberry321/13-kubernetes-config_backend
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: stage
spec:
  ports:
    - name: frontend
      port: 8000
      targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: stage
spec:
  ports:
    - name: backend
      port: 9000
      targetPort: 9000
  selector:
    app: backend
  type: ClusterIP
